apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cagea1-prod
resources:
- secret.yaml
- ../../../base/cagea1
images:
- name: ghcr.io/taeboranger/cagea1.com
  newName: ghcr.io/taeboranger/cagea1.com
  newTag: main
- name: lightstone1/cagea1.com-prod
  newTag: 661ba81f2983c953ea26592a28b3ec8beebb00f9
