apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cagea1-prod
resources:
- vault-static-secret.yaml
- persistent-volume-claim.yaml
- ../../../base/cagea1
images:
- name: lightstone1/cagea1.com-prod
  newTag: d9d6d6c09b74af316c0c71f7cf8f48fc644b2dd8
