apiVersion: v1
kind: Secret
metadata:
  name: cagea1-secret
  annotations:
    avp.kubernetes.io/path: kv/data/cagea1-com-prod-secret
type: Opaque
stringData:
  SITE_USERNAME: <site-username>
  SITE_PASSWORD: <site-password>
  SITE_AUTH_SECRET: <site-auth-secret>
  GITHUB_USERNAME: <github-username>
  GITHUB_TOKEN: <github-token>
