apiVersion: v1
kind: ServiceAccount
metadata:
  name: cagea1-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cagea1-vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: vault-secrets-operator-system/cagea1-vault
  kubernetes:
    role: cagea1-vso
    serviceAccount: cagea1-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cagea1-runtime
spec:
  type: kv-v2
  mount: kv
  path: cagea1-com-prod-secret
  refreshAfter: 1h
  vaultAuthRef: cagea1-vault-auth
  destination:
    create: true
    overwrite: true
    name: cagea1-secret
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        SITE_USERNAME:
          text: '{{ default (get .Secrets "site-username") (get .Secrets "SITE_USERNAME") }}'
        SITE_PASSWORD:
          text: '{{ default (get .Secrets "site-password") (get .Secrets "SITE_PASSWORD") }}'
        SITE_AUTH_SECRET:
          text: '{{ default (get .Secrets "site-auth-secret") (get .Secrets "SITE_AUTH_SECRET") }}'
        GITHUB_USERNAME:
          text: '{{ default (get .Secrets "github-username") (get .Secrets "GITHUB_USERNAME") }}'
        GITHUB_TOKEN:
          text: '{{ default (get .Secrets "github-token") (get .Secrets "GITHUB_TOKEN") }}'
